### PR TITLE
Update Info.plist

### PR DESCRIPTION
**Pull request by samijomcp**

### CODE REVIEW

**Comment by rockwood** [comment]
Sorry I'm not sure what this pull request is for. Could you explain?

**Comment by samijomcp** [comment]
Sorry Kevin, I too am a little confused!

I am new to GitHub and joined when I saw your program. I am trying to
covert fcpxml files so I can see the market times.

I'm not sure how to begin the process. Would you mind helping me out?

**Comment by rockwood** [comment]
@samijomcp No problem. You can use the app my going to the [homepage](https://github.com/rockwood/fcpx-Marker-Converter) and clicking the "Download ZIP" button. Just unpack the zip and open Markers.app. Make sure your computer is setup to [allow apps from unknown developers](http://rampagedev.wordpress.com/os-x-tweaks/app-cant-be-opened-because-it-was-not-downloaded-from-the-mac-app-store-fix-2/)

**Comment by samijomcp** [comment]
Oh my goodness! You just saved me so much time!!!

Thank you so so much!!!

**Pull request closed without merging**
